### ISSUE TITLE
add active and usageLimit fields in coupon2

### ISSUE THREAD

**Issue by pinnareet** [thanakijwanavit/villaMasterSchema#123]
```yaml
active:
  type: boolean
usageLimit:
  type: integer
```

usageLimit is already in dynamodb but it's not in the schema
